[build]
    jobs      = 1                 # number of parallel jobs, defaults to # of CPUs
    rustc     = "rustc"           # the rust compiler tool - I intend to use extern C's
    rustflags = ["-Z", "mut_ref"] # custom flags to pass to all compiler invocations
